/*
 * File: app/view/ctn_statistics_view.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.ctn_statistics_view', {
    extend: 'Ext.Container',
    alias: 'widget.ctn_statistics_view',

    requires: [
        'facturaElecWeb.view.ctn_statistics_viewViewModel',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'ctn_statistics_view'
    },
    id: 'ctn_statistics_view',
    padding: 20,

    items: [
        {
            xtype: 'dataview',
            height: '100%',
            width: '100%',
            scrollable: false,
            itemTpl: [
                '<tpl if=\'[Ext.getCmp("ctn_statistics_view").getViewModel().get("filtro")] == \"ADMIN\"\'>',
                '',
                '    <div class="row w-100 h-50">',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card" ><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Usuarios</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{usuario}</h1></div>',
                '            </div>',
                '        </div>',
                '        <div class="col-md-1"></div>',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card"><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Facturas</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{factura}</h1></div>',
                '            </div>',
                '        </div>',
                '        <div class="col-md-1"></div>',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card" ><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Productos</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{producto}</h1></div>',
                '            </div>',
                '        </div>',
                '    </div>',
                '',
                '    <div class="row w-100" style="margin: 20px 0px 0px">',
                '        <div class="col-md-3"></div>',
                '',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card"><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Clientes</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{cliente}</h1></div>',
                '            </div>',
                '        </div>',
                '',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card" ><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Empresas</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{empresa}</h1></div>',
                '            </div>',
                '        </div>',
                '',
                '        <div class="col-md-3"></div>',
                '    </div>',
                '',
                '</tpl>',
                '',
                '<tpl if=\'[Ext.getCmp("ctn_statistics_view").getViewModel().get("filtro")] == \"USER\"\'>',
                '',
                '    <div class="row w-100 h-50" style="margin:150px 0px 0px">',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card"><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Facturas</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{factura}</h1></div>',
                '            </div>',
                '        </div>',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card" ><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Productos</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{producto}</h1></div>',
                '            </div>',
                '        </div>',
                '',
                '',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card"><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Clientes</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{cliente}</h1></div>',
                '            </div>',
                '        </div>',
                '',
                '        <div class="col-md-3">',
                '            <div class="card border-warning mx-sm-1 p-3">',
                '                <div class="card border-warning shadow text-warning p-3 my-card" ><span class="fa fa-eye" aria-hidden="true"></span></div>',
                '                <div class="text-warning text-center mt-3"><h4>Empresas</h4></div>',
                '                <div class="text-warning text-center mt-2"><h1>{empresa}</h1></div>',
                '            </div>',
                '        </div>',
                '    </div>',
                '</tpl>',
                ''
            ],
            store: 'store_info_count'
        }
    ],

    fn_find_statistcs: function(filter) {
        var storeInfo = Ext.getStore('store_info_count');
        storeInfo.proxy.extraParams ={
            role: filter
        };


        storeInfo.load({
            params:{
                role:filter
            },
            callback: function(records, operation, success) {
                if(success){
                    var noAlmacenado=false;
                    var total = storeInfo.totalCount;
                    if(total === 0){
                        Ext.getCmp('ctn_statistics_view').getViewModel().set('filtro',null);
                        Ext.toast('No hay resultados para la búsqueda',1000);
                    }

                }
            }
        });
    }

});