/*
 * File: app/view/ctn_client_view.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.ctn_client_view', {
    extend: 'Ext.Container',
    alias: 'widget.ctn_client_view',

    requires: [
        'facturaElecWeb.view.ctn_client_viewViewModel',
        'facturaElecWeb.view.ctn_client_viewViewController',
        'facturaElecWeb.view.grd_client',
        'Ext.field.Search',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.grid.Grid'
    ],

    controller: 'ctn_client_view',
    viewModel: {
        type: 'ctn_client_view'
    },
    id: 'ctn_client_view',
    layout: 'hbox',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            flex: 2.5,
            cls: 'borde-gestion-info',
            name: 'ctn_info_client',
            padding: '50 0 50 0',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    flex: 0.5,
                    name: 'ctn_search_client',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'searchfield',
                            validators: function(value) {
                                if(!/^([0-9])*$/.test(value)){
                                    return "El documento debe ser  un número entero";
                                }else if(value<0){
                                    return "La cantidad de caracteres ingresada es inválida";

                                }else{
                                    return true;
                                }
                            },
                            itemId: 'search_field_client',
                            name: 'search_field_cliente',
                            width: '70%',
                            labelCls: 'my-text',
                            placeholder: 'Buscar por documento',
                            listeners: {
                                keyup: 'onSearch_field_clientKeyup'
                            }
                        }
                    ]
                },
                {
                    xtype: 'dataview',
                    id: 'data_view_client',
                    padding: '0 0 0 30',
                    itemTpl: [
                        '<div class="table-generic">',
                        '    <table>',
                        '',
                        '        <tbody >',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Tipo de documento:</th>',
                        '',
                        '                <td class="row-generic">{tipoDocumento}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Documento:</th>',
                        '',
                        '                <td class="row-generic">{documento}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Nombre:</th>',
                        '',
                        '                <td class="row-generic">{nombre}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Pais:</th>',
                        '',
                        '                <td class="row-generic">{pais}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Ciudad:</th>',
                        '',
                        '                <td class="row-generic">{ciudad}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Dirección:</th>',
                        '',
                        '                <td class="row-generic">{direccion}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Telefono:</th>',
                        '',
                        '                <td class="row-generic">{telefono}</td>',
                        '',
                        '            </tr>',
                        '            <tr>',
                        '',
                        '                <th class="row-generic">Correo:</th>',
                        '',
                        '                <td class="row-generic">{correo}</td>',
                        '',
                        '            </tr>',
                        '        </tbody>',
                        '    </table>',
                        '</div>'
                    ]
                },
                {
                    xtype: 'container',
                    flex: 0.8,
                    name: 'ctn_bottons_client',
                    padding: 5,
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getCmp('ctn_client_view').fn_find_client(null);
                                Ext.getCmp('data_view_client').setStore('');
                                Ext.ComponentQuery.query('[itemId=search_field_client]')[0].setValue('');
                                Ext.getCmp('ctn_client_view').getViewModel().set('filtro',null);
                            },
                            cls: 'color-buttons',
                            height: 50,
                            id: 'btn_refresh_client',
                            ui: 'round',
                            width: 50,
                            margin: '0 5 0 0',
                            tooltip: 'Refrescar',
                            iconCls: 'x-fa fa-refresh'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var filter = Ext.getCmp('ctn_client_view').getViewModel().get('filtro');
                                if(filter != null){
                                    Ext.Msg.show({
                                        title: 'Confirmación',
                                        message: "¿Esta seguro de eliminar el cliente con documento "+filter+"?",
                                        width: 300,
                                        closable: false,
                                        buttons: [{
                                            text: 'No',
                                            itemId: 'no'
                                        }, {
                                            text: 'Si',
                                            itemId: 'yes'
                                        }],
                                        multiline: false,
                                        fn: function (buttonValue, inputText, showConfig) {
                                            if(buttonValue === "yes"){


                                                Ext.Ajax.request({
                                                    url: 'clienteController/eliminarCliente?documento='+filter,
                                                    method: 'GET',
                                                    success: function(response, opts) {
                                                        Ext.getCmp('ctn_client_view').fn_find_client(null);
                                                        Ext.getCmp('data_view_client').setStore('');
                                                        Ext.getCmp('ctn_client_view').getViewModel().set('filtro',null);
                                                        Ext.ComponentQuery.query('[itemId=search_field_client]')[0].setValue('');
                                                        var info =Ext.getCmp('ctn_statistics_view').getViewModel().get('filtro');
                                                        Ext.getCmp('ctn_statistics_view').fn_find_statistcs(info);
                                                        Ext.toast('Exito al eliminar', 1000);

                                                    },
                                                    failure: function(response, opts) {
                                                        Ext.toast('Error al llevar a cabo el proceso, El cliente esta vinculado a una factura', 1000);
                                                    }
                                                });
                                            }else{
                                                this.close();
                                            }
                                        },
                                        icon: Ext.Msg.QUESTION
                                    });


                                }else{
                                    Ext.toast('Seleccione un cliente', 1000);
                                }
                            },
                            cls: 'color-buttons',
                            height: 50,
                            name: 'btn_delete_client',
                            ui: 'round',
                            width: 50,
                            margin: '0 5 0 0',
                            tooltip: 'Eliminar cliente',
                            iconCls: 'x-fa fa-trash blackIcon'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var filter = Ext.getCmp('ctn_client_view').getViewModel().get('filtro');
                                if(filter != null){
                                    var vtn = Ext.create('widget.vtn_generar_cliente',{
                                        title : '¡ EDITAR CLIENTE !'
                                    }).show();
                                    var store = Ext.getStore('store_gestion_cliente');
                                    var record = store.findRecord('documento', filter, 0, false, true, true);
                                    var form =Ext.getCmp('frm_clientes');
                                    form.setRecord(record);
                                }else{
                                    Ext.toast('Seleccione un cliente', 1000);
                                }
                            },
                            cls: 'color-buttons',
                            height: 50,
                            name: 'btn_edit_client',
                            ui: 'round',
                            width: 50,
                            margin: '0 5 0 0',
                            tooltip: 'Editar cliente',
                            iconCls: 'x-fa fa-pencil-square-o blackIcon'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var vtn = Ext.create('widget.vtn_generar_cliente',{
                                    title : '¡ NUEVO CLIENTE !'
                                }).show();
                            },
                            cls: 'color-buttons',
                            height: 50,
                            name: 'btn_add_client',
                            ui: 'round',
                            width: 50,
                            tooltip: 'Crear un nuevo cliente',
                            iconCls: 'x-fa fa-plus blackIcon'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 4.5,
            name: 'ctn_grid_client',
            padding: '30 30 0 30',
            items: [
                {
                    xtype: 'container',
                    height: '100%',
                    name: 'ctn_grid_medium_ client',
                    width: '100%',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: '70%',
                            name: 'ctn_grid_internal_client',
                            width: '100%',
                            items: [
                                {
                                    xtype: 'grd_client',
                                    itemId: 'grd_client_view'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        initialize: {
            fn: 'onCtn_client_viewInitialize',
            scope: 'controller'
        }
    },

    onSearch_field_clientKeyup: function(textfield, e, eOpts) {
        var filter= textfield.getValue();
        if (e.event.keyCode == 13){
            Ext.getCmp('ctn_client_view').fn_find_client(filter);
            Ext.getCmp('data_view_client').setStore('store_gestion_cliente');
            Ext.getCmp('ctn_client_view').getViewModel().set('filtro',filter);
            //debugger;
        }
        if(!textfield.getValue()){
            Ext.getCmp('ctn_client_view').fn_find_client(null);
            Ext.getCmp('data_view_client').setStore('');

        }
    },

    fn_find_client: function(filter) {
        var storeClient = Ext.getStore('store_gestion_cliente');
        storeClient.proxy.extraParams ={
            filtro : filter
        };


        storeClient.load({
            params:{
                filtro:filter
            },
            callback: function(records, operation, success) {
                if(success){
                    var noAlmacenado=false;
                    var total = storeClient.totalCount;
                    if(total === 0){
                       // Ext.getCmp('ctn_client_view').fn_find_client(null);
                        Ext.getCmp('data_view_client').setStore('');
                        Ext.ComponentQuery.query('[itemId=search_field_client]')[0].setValue('');
                        Ext.getCmp('ctn_client_view').getViewModel().set('filtro',null);
                        Ext.toast('No hay resultados para la búsqueda',1000);
                    }

                }
            }
        });
    }

});