/*
 * File: app/view/ctn_account.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.ctn_account', {
    extend: 'Ext.Container',
    alias: 'widget.ctn_account',

    requires: [
        'facturaElecWeb.view.ctn_accountViewModel',
        'facturaElecWeb.view.ctn_accountViewController',
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.field.Password',
        'Ext.Button'
    ],

    controller: 'ctn_account',
    viewModel: {
        type: 'ctn_account'
    },
    id: 'ctn_account',
    layout: 'hbox',

    items: [
        {
            xtype: 'container',
            name: 'ctn_form_account',
            width: '40%',
            displayed: true,
            padding: '50 20 0 20',
            items: [
                {
                    xtype: 'container',
                    name: 'ctn_icon_account',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            cls: 'image-generic-frm',
                            name: 'image_account',
                            src: 'https://image.flaticon.com/icons/svg/74/74472.svg'
                        }
                    ]
                },
                {
                    xtype: 'formpanel',
                    id: 'frmAccount',
                    name: 'frmAccount',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            itemId: 'idUser',
                            label: 'Field',
                            labelCls: 'my-text'
                        },
                        {
                            xtype: 'textfield',
                            validators: function(value) {
                                if(value.length>100){
                                    return "El nombre supera el tamaño permitido (100)";
                                }else if(/^([0-9])*$/.test(value)){
                                    return "El nombre tiene caracteres invalidos.(0-9)";
                                }else{
                                    return true;
                                }
                            },
                            itemId: 'firstname',
                            name: 'firstname',
                            width: '70%',
                            label: 'Nombre',
                            labelCls: 'my-text',
                            required: true,
                            requiredMessage: 'El nombre es obligatorio'
                        },
                        {
                            xtype: 'textfield',
                            validators: function(value) {
                                if(value.length>100){
                                    return "El apellido supera el tamaño permitido (100)";
                                }else if(/^([0-9])*$/.test(value)){
                                    return "El apellido tiene caracteres invalidos.(0-9)";
                                }else{
                                    return true;
                                }
                            },
                            itemId: 'lastname',
                            name: 'lastname',
                            width: '70%',
                            label: 'Apellido',
                            labelCls: 'my-text',
                            required: true,
                            requiredMessage: 'El apellido es obligatorio'
                        },
                        {
                            xtype: 'textfield',
                            validators: function(value) {
                                if ((!Ext.isEmpty(value)) && (Ext.isEmpty(value.trim()))) {
                                    return "El campo correo no admite espacios";
                                }else if(value.length>100){
                                    return "El correo supera el tamaño permitido (100)";
                                }else if(!/^(")?(?:[^\."])(?:(?:[\.])?(?:[\w\-!#$%&'*+\/=?\^_`{|}~]))*\1@(\w[\-\w]*\.){1,5}([A-Za-z]){2,6}$/.test(value)){
                                    return "Correo invalido.(demo@demo.com)";
                                }else{
                                    return true;
                                }
                            },
                            itemId: 'email',
                            name: 'email',
                            width: '70%',
                            label: 'Correo electronico',
                            labelCls: 'my-text',
                            required: true,
                            requiredMessage: 'El correo electronico es obligatorio'
                        },
                        {
                            xtype: 'passwordfield',
                            validators: function(value) {
                                if(value.length<8 || value.length>20){
                                    return "La contraseña debe tener entre 8 y 20 caracteres";
                                }else {
                                    return true;
                                }
                            },
                            itemId: 'password',
                            name: 'password',
                            width: '70%',
                            label: 'Contraseña',
                            labelCls: 'my-text',
                            required: true,
                            requiredMessage: 'La contraseña es obligatoria',
                            placeholder: 'Ingrese o cambie su contraseña'
                        },
                        {
                            xtype: 'container',
                            name: 'ctn_buttons_account',
                            margin: '50 0 0 0',
                            layout: {
                                type: 'hbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        Ext.getCmp('ctn_account').fn_cerrar_sesion();
                                    },
                                    cls: 'blackIcon',
                                    tooltip: 'Cerrar sesión',
                                    text: 'Cerrar sesión'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var form = Ext.getCmp('frmAccount');
                                        var values = form.getValues();
                                        var id = Ext.ComponentQuery.query('[itemId=idUser]')[0].getValue();
                                        var oldEmail = Ext.getCmp('ctn_account').getViewModel().get('oldEmail');

                                        if (form.validate()){
                                            Ext.Ajax.request({
                                                url: 'sesionUsuario/actualizarUsuario',
                                                method: 'POST',
                                                params: {
                                                    active: values.activo,
                                                    email: values.email,
                                                    oldEmail:oldEmail,
                                                    firstname: values.firstname,
                                                    id: id,
                                                    lastname: values.lastname,
                                                    password: values.password
                                                },
                                                success: function(response, opts) {
                                                    var respuesta = JSON.parse(response.responseText);
                                                    if(respuesta.success){
                                                        Ext.toast('Edición Exitosa', 1000);
                                                        Ext.getCmp('ctn_account').fn_cerrar_sesion();
                                                    }else{
                                                        Ext.toast(respuesta.message, 1000);
                                                    }


                                                },
                                                failure: function(response, opts) {
                                                    Ext.toast('Error al llevar a cabo el proceso', 1000);
                                                }
                                            });
                                        }
                                    },
                                    cls: 'blackIcon',
                                    tooltip: 'Guardar los cambios',
                                    text: 'Guardar'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            cls: 'fondoPrincipal',
            name: 'ctn_imagen_account',
            width: '60%'
        }
    ],
    listeners: {
        initialize: 'onCtn_accountInitialize'
    },

    fn_cerrar_sesion: function() {
        Ext.Ajax.request({
            url: '/logout',
            method: 'GET',
            success: function(response, opts) {

                Ext.toast('Exito cerrar sesion', 1000);
                 window.location.href = "";

            },
            failure: function(response, opts) {
                Ext.toast('Error al cerrar sesion', 1000);
            }
        });
    }

});