/*
 * File: app/view/ctn_user_viewViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.ctn_user_viewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.ctn_user_view',

    onContainerInitialize: function(component, eOpts) {
        Ext.getStore('store_gestion_usuarios').load();
    }

});