/*
 * File: app/view/ctn_accountViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.ctn_accountViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.ctn_account',

    onCtn_accountInitialize: function(component, eOpts) {
        Ext.Ajax.request({
            url: '/sesionUsuario/usuario',
            method: 'GET',
            success: function(response, opts) {
                var user = JSON.parse(response.responseText);

                Ext.ComponentQuery.query('[itemId=firstname]')[0].setValue(user.data.firstname);
                Ext.ComponentQuery.query('[itemId=lastname]')[0].setValue(user.data.lastname);
                Ext.ComponentQuery.query('[itemId=email]')[0].setValue(user.data.email);
                Ext.ComponentQuery.query('[itemId=idUser]')[0].setValue(user.data.id);
                Ext.ComponentQuery.query('[itemId=password]')[0].setValue('');
                Ext.getCmp('ctn_account').getViewModel().set('oldEmail',user.data.email);
                Ext.getCmp('ctn_statistics_view').getViewModel().set('filtro',user.data.roles[0].role);
                Ext.getCmp('ctn_statistics_view').fn_find_statistcs(user.data.roles[0].role);
                if(user.data.roles[0].role != 'ADMIN'){
                    Ext.getCmp('tbp_menu').items.items[2].hide();
                    Ext.getCmp('tbp_menu').items.items[2].tab.hide();
                }
            },
            failure: function(response, opts) {
            }
        });
    }

});