/*
 * File: app/view/grd_user.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.grd_user', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grd_user',

    requires: [
        'facturaElecWeb.view.grd_userViewModel',
        'Ext.grid.column.Text'
    ],

    viewModel: {
        type: 'grd_user'
    },
    height: '100%',
    id: 'grd_user',
    width: '100%',
    scrollable: 'vertical',
    layout: 'vbox',
    store: 'store_gestion_usuarios',
    defaultListenerScope: true,

    columns: [
        {
            xtype: 'textcolumn',
            width: '25%',
            dataIndex: 'firstname',
            text: 'Nombre'
        },
        {
            xtype: 'textcolumn',
            width: '25%',
            dataIndex: 'lastname',
            text: 'Apellido'
        },
        {
            xtype: 'textcolumn',
            width: '30%',
            dataIndex: 'email',
            text: 'E-mail'
        },
        {
            xtype: 'textcolumn',
            width: '20%',
            dataIndex: 'active',
            text: 'Activo'
        }
    ],
    listeners: {
        select: 'onGrd_userSelect'
    },

    onGrd_userSelect: function(dataview, selected, eOpts) {
        var filter = selected[0].data.id;
        Ext.getCmp('ctn_user_view').fn_find_user(selected[0].data.email);
        Ext.getCmp('data_view_user').setStore('store_gestion_usuarios');
        Ext.getCmp('ctn_user_view').getViewModel().set('filtro',filter);
        Ext.getCmp('ctn_user_view').getViewModel().set('oldEmail',selected[0].data.email);
    }

});