/*
 * File: app/view/grd_invoice.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.grd_invoice', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grd_invoice',

    requires: [
        'facturaElecWeb.view.grd_invoiceViewModel',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'grd_invoice'
    },
    height: '100%',
    id: 'grd_invoice',
    width: '100%',
    scrollable: 'vertical',
    layout: 'vbox',
    store: 'store_gestion_all_factura',
    defaultListenerScope: true,

    columns: [
        {
            xtype: 'gridcolumn',
            width: '20%',
            dataIndex: 'codigo',
            text: 'Codigo'
        },
        {
            xtype: 'gridcolumn',
            width: '20%',
            dataIndex: 'fechaCreacion',
            formatter: 'date("Y-m-d")',
            text: 'Fecha'
        },
        {
            xtype: 'gridcolumn',
            width: '20%',
            dataIndex: 'nombreCliente',
            text: 'Cliente'
        },
        {
            xtype: 'gridcolumn',
            width: '20%',
            dataIndex: 'nombreEmpresa',
            text: 'Empresa'
        },
        {
            xtype: 'numbercolumn',
            width: '20%',
            dataIndex: 'total',
            text: 'Total'
        }
    ],
    listeners: {
        select: 'onGridSelect'
    },

    onGridSelect: function(dataview, selected, eOpts) {
        var filter = selected[0].data.codigo;
        Ext.getCmp('ctn_invoice_view').fn_find_invoice(filter);
        Ext.getCmp('ctn_invoice_view').fn_find_product_invoice(filter);
        Ext.getCmp('data_view_invoice').setStore('store_gestion_all_factura');
        Ext.getCmp('ctn_invoice_view').getViewModel().set('filtro',filter);
    }

});