/*
 * File: app/view/grd_product.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.grd_product', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.grd_product',

    requires: [
        'facturaElecWeb.view.grd_productViewModel',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'grd_product'
    },
    height: '100%',
    itemId: 'grd_product',
    width: '100%',
    scrollable: 'vertical',
    layout: 'vbox',
    store: 'store_gestion_producto',
    defaultListenerScope: true,

    columns: [
        {
            xtype: 'gridcolumn',
            width: '20%',
            align: 'center',
            dataIndex: 'codigo',
            text: 'Codigo'
        },
        {
            xtype: 'gridcolumn',
            width: '30%',
            align: 'center',
            dataIndex: 'nombre',
            text: 'Nombre'
        },
        {
            xtype: 'gridcolumn',
            width: '20%',
            align: 'center',
            dataIndex: 'marca',
            text: 'Marca'
        },
        {
            xtype: 'numbercolumn',
            width: '30%',
            align: 'center',
            dataIndex: 'precio',
            text: 'Precio'
        }
    ],
    listeners: {
        select: 'onGridSelect'
    },

    onGridSelect: function(dataview, selected, eOpts) {
        var filter = selected[0].data.codigo;
        if((Ext.getCmp('vtn_seleccionar_detalle_factura')) && (Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().get('detalleProducto') === false)){
            if((Ext.getStore('store_gestion_producto_factura').find('codigo', filter, 0, false, true, true)) === -1){
                var store = Ext.getStore('store_gestion_producto');
                store.findRecord('codigo', filter, 0, false, true, true);
                var vtn = Ext.create('widget.vtn_generar_producto',{
                    title : '¡ AGREGAR PRODUCTO !'
                }).show();


                var form =Ext.getCmp('frm_productos');

                var record = store.findRecord('codigo', filter, 0, false, true, true);
                form.setRecord(record);
                Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleProducto',false);
                Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleCrearFactura',true);
                Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleSaveFactura',false);


            }else{
                Ext.toast('El producto ya ha sido agregado', 1000);
            }
        }else{

            Ext.getCmp('ctn_product_view').fn_find_product(filter);
            Ext.getCmp('data_view_product').setStore('store_gestion_producto');
            Ext.getCmp('ctn_product_view').getViewModel().set('filtro',filter);
        }
    }

});