/*
 * File: app/view/vtn_generar_factura.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.vtn_generar_factura', {
    extend: 'Ext.Dialog',
    alias: 'widget.vtn_generar_factura',

    requires: [
        'facturaElecWeb.view.vtn_generar_facturaViewModel',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.Button',
        'Ext.field.Display',
        'Ext.grid.Grid',
        'Ext.grid.column.Number',
        'Ext.field.Number'
    ],

    viewModel: {
        type: 'vtn_generar_factura'
    },
    height: '90%',
    id: 'vtn_generar_factura',
    itemId: 'vtn_generar_factura',
    name: 'vtn_generar_factura',
    width: '60%',
    displayed: true,
    scrollable: false,
    closable: true,
    closeToolText: 'Cerra',
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'formpanel',
            height: '100%',
            id: 'frm_factura',
            width: '100%',
            scrollable: false,
            items: [
                {
                    xtype: 'container',
                    name: 'ctn_imagen_factura',
                    margin: '-7 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            cls: 'image-generic-frm',
                            name: 'img_factura',
                            src: 'https://image.flaticon.com/icons/svg/1849/1849086.svg'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: '50%',
                    name: 'ctn_frm_factura',
                    scrollable: 'vertical',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            name: 'ctn_detalle_factura',
                            width: '100%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'txt_cliente_factura',
                                    name: 'documentoCliente',
                                    width: '30%',
                                    docked: 'left',
                                    label: 'Documento cliente',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Seleccione un cliente',
                                    editable: false
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var vtn = Ext.create('widget.vtn_seleccionar_detalle_factura',{
                                            title : '¡ SELECIONAR CLIENTE !'
                                        }).show();
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleCliente',false);
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleEmpresa',true);
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleProducto',true);
                                    },
                                    cls: 'color-buttons',
                                    height: 30,
                                    name: 'btn_cliente_factura',
                                    ui: 'round',
                                    width: 30,
                                    docked: 'left',
                                    tooltip: 'Seleccionar cliente',
                                    iconCls: 'x-fa fa-plus blackIcon'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'txt_empresa_factura',
                                    name: 'nitEmpresa',
                                    width: '30%',
                                    docked: 'right',
                                    margin: '0 0 0 10',
                                    label: 'Nit empresa',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Seleccione una empresa',
                                    editable: false
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var vtn = Ext.create('widget.vtn_seleccionar_detalle_factura',{
                                            title : '¡ SELECIONAR EMPRESA !'
                                        }).show();
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleCliente',true);
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleEmpresa',false);
                                        Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleProducto',true);
                                    },
                                    cls: 'color-buttons',
                                    height: 30,
                                    name: 'btn_empresa_factura',
                                    ui: 'round',
                                    width: 30,
                                    docked: 'right',
                                    tooltip: 'Seleccionar empresa',
                                    iconCls: 'x-fa fa-plus blackIcon'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            name: 'ctn_productos_factura',
                            width: '100%',
                            margin: '10 0 0 0',
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    name: 'ctn_detalle_producto',
                                    margin: '0 0 10 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'center',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            label: 'Productos',
                                            labelCls: 'my-text'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, e) {
                                                var vtn = Ext.create('widget.vtn_seleccionar_detalle_factura',{
                                                    title : '¡ SELECIONAR PRODUCTO !'
                                                }).show();
                                                Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleCliente',true);
                                                Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleEmpresa',true);
                                                Ext.getCmp('vtn_seleccionar_detalle_factura').getViewModel().set('detalleProducto',false);

                                            },
                                            cls: 'color-buttons',
                                            height: 30,
                                            name: 'btn_agregar_producto',
                                            ui: 'round',
                                            width: 30,
                                            iconCls: 'x-fa fa-plus blackIcon'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'grid',
                                    height: 200,
                                    id: 'grd_productos_factura',
                                    itemId: 'mygrid1',
                                    name: 'productos',
                                    width: '100%',
                                    scrollable: 'vertical',
                                    store: 'store_gestion_producto_factura',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '20%',
                                            dataIndex: 'nombre',
                                            text: 'Nombre'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            dataIndex: 'marca',
                                            text: 'Marca'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            dataIndex: 'garantia',
                                            text: 'Garantia'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: '20%',
                                            dataIndex: 'precio',
                                            text: 'Precio'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            dataIndex: 'cantidad',
                                            text: 'Cantidad'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: '15%',
                                            dataIndex: 'totalProducto',
                                            text: 'Total'
                                        }
                                    ],
                                    listeners: {
                                        refresh: 'onGrd_productos_facturaRefresh',
                                        select: 'onGrd_productos_facturaSelect'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    name: 'ctn_total_factura',
                    margin: '10 0 3 0',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            name: 'ctn_internal_total_factura',
                            width: '30%',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    height: '10%',
                                    id: 'txt_total_factura',
                                    name: 'total',
                                    docked: 'left',
                                    label: 'Total',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Seleccione un producto',
                                    clearable: false,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            name: 'ctn_buttons_factura',
                            width: '40%',
                            layout: 'center',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        debugger;
                                        var form = Ext.getCmp('frm_factura');
                                        var values = form.getValues();
                                        if (form.validate()){
                                            var storeData = Ext.getStore('store_gestion_producto_factura').data;
                                            var JSONData = [];
                                            for(var i = 0; i < storeData.length; i++){
                                                JSONData.push(storeData.items[i].data);
                                            }
                                            JSONData = JSON.stringify(JSONData);
                                            if(values.codigo === null){
                                                Ext.ComponentQuery.query('[itemId=txt_codigo_factura]')[0].setValue(0);
                                            }
                                            Ext.getCmp('grd_view_product_invoice').hide();

                                            form.submit({

                                                url: "facturaController/agregarFactura",
                                                params: {
                                                    producto: JSONData
                                                },

                                                waitMsg: 'Espere...',
                                                success: function (fp, o) {
                                                    Ext.getStore('store_gestion_producto_factura').data.clear();
                                                    Ext.getCmp('ctn_invoice_view').fn_find_invoice(null);
                                                    Ext.getCmp('data_view_invoice').setStore('');
                                                    // Ext.getCmp('grd_view_product_invoice').setHidden(true);
                                                    Ext.ComponentQuery.query('[itemId=search_field_invoice]')[0].setValue('');
                                                    Ext.getCmp('ctn_invoice_view').getViewModel().set('filtro',null);
                                                    var filter =Ext.getCmp('ctn_statistics_view').getViewModel().get('filtro');
                                                    Ext.getCmp('ctn_statistics_view').fn_find_statistcs(filter);
                                                    Ext.getCmp('vtn_generar_factura').close();
                                                    Ext.toast('Proceso exitoso', 1000);
                                                },
                                                failure: function(response, opts) {
                                                    Ext.toast('Error al llevar a cabo el proceso', 1000);
                                                }
                                            });

                                        }else{
                                            Ext.toast('Error al validar el formulario!', 1000);
                                        }

                                    },
                                    cls: 'color-buttons',
                                    height: 50,
                                    name: 'btn_factura',
                                    ui: 'round',
                                    width: 50,
                                    tooltip: 'Continuar proceso',
                                    iconCls: 'x-fa fa-check blackIcon'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            name: 'ctn_codigo_factura',
                            width: '30%',
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txt_codigo_factura',
                                    name: 'codigo',
                                    label: 'Codigo',
                                    labelCls: 'my-text',
                                    clearable: false,
                                    editable: false,
                                    bind: {
                                        hidden: '{inhabilitarCodigo}'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onGrd_productos_facturaRefresh: function(dataview, eOpts) {
        var storeData = Ext.getStore('store_gestion_producto_factura').data;
        var totalFactura = 0;
        for(var i = 0; i < storeData.length; i++){
            totalFactura = totalFactura + storeData.items[i].data.totalProducto;
        }if(totalFactura === 0){
            Ext.getCmp('txt_total_factura').setValue(null);
        }else{
            Ext.getCmp('txt_total_factura').setValue(totalFactura);
        }
    },

    onGrd_productos_facturaSelect: function(dataview, selected, eOpts) {
        var filter = selected[0].data.codigo;
        var store = Ext.getStore('store_gestion_producto_factura');
        store.findRecord('codigo', filter, 0, false, true, true);
        var vtn = Ext.create('widget.vtn_generar_producto',{
            title : '¡ EDITAR PRODUCTO !'
        }).show();


        var form =Ext.getCmp('frm_productos');

        var record = store.findRecord('codigo', filter, 0, false, true, true);
        form.setRecord(record);
        Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleProducto',false);
        Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleCrearFactura',false);
        Ext.getCmp('vtn_generar_producto').getViewModel().set('detalleSaveFactura',true);

    }

});