/*
 * File: app/view/vtn_generar_usuario.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.view.vtn_generar_usuario', {
    extend: 'Ext.Dialog',
    alias: 'widget.vtn_generar_usuario',

    requires: [
        'facturaElecWeb.view.vtn_generar_usuarioViewModel',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.field.ComboBox',
        'Ext.field.Password',
        'Ext.Button'
    ],

    viewModel: {
        type: 'vtn_generar_usuario'
    },
    height: '90%',
    id: 'vtn_generar_usuario',
    itemId: 'vtn_generar_usuario',
    name: 'vtn_generar_usuario',
    width: '60%',
    displayed: true,
    scrollable: 'vertical',
    layout: 'center',
    closable: true,
    closeToolText: 'Cerrar',
    titleAlign: 'center',

    items: [
        {
            xtype: 'formpanel',
            id: 'frmUser',
            width: '100%',
            items: [
                {
                    xtype: 'container',
                    name: 'ctn_image_user',
                    margin: '-7 0 10 0',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            cls: 'image-generic-frm',
                            name: 'image_user',
                            src: 'https://image.flaticon.com/icons/svg/74/74472.svg'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    name: 'ctn_frm_user',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            name: 'ctn_column_left_user',
                            width: '45%',
                            docked: 'left',
                            margin: '0 10 0 0',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        if(value.length>100){
                                            return "El nombre supera el tamaño permitido (100)";
                                        }else if(/^([0-9])*$/.test(value)){
                                            return "El nombre tiene caracteres invalidos.(0-9)";
                                        }else{
                                            return true;
                                        }
                                    },
                                    name: 'firstname',
                                    width: '100%',
                                    label: 'Nombre',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Digite un nombre'
                                },
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        var store= Ext.getStore('store_gestion_usuarios');
                                        var Existente=false;
                                        var idUsuario=null;
                                        var idForm=Ext.getCmp('frmUser').getRecord()?Ext.getCmp('frmUser').getRecord().id :null;
                                        store.each(function(record){
                                            if(value == record.data.correo){
                                                Existente=true;
                                                idUsuario=record.id;
                                            }
                                        });

                                        if ((!Ext.isEmpty(value)) && (Ext.isEmpty(value.trim()))) {
                                            return "El campo correo no admite espacios";
                                        }else if(value.length>100){
                                            return "El correo supera el tamaño permitido (100)";
                                        }else if(!/^(")?(?:[^\."])(?:(?:[\.])?(?:[\w\-!#$%&'*+\/=?\^_`{|}~]))*\1@(\w[\-\w]*\.){1,5}([A-Za-z]){2,6}$/.test(value)){
                                            return "Correo invalido.(demo@demo.com)";
                                        }else if(Existente && idUsuario!=idForm){
                                            return "Ya existe un usuario con este correo";
                                        }else{
                                            return true;
                                        }
                                    },
                                    name: 'email',
                                    width: '100%',
                                    label: 'E-mail',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Digite un E-Mail'
                                },
                                {
                                    xtype: 'combobox',
                                    name: 'active',
                                    width: '100%',
                                    label: 'Estado',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Seleccione el estado del usuario',
                                    displayField: 'nombre',
                                    store: [
                                        {
                                            active: 0,
                                            nombre: 'Deshabilitado'
                                        },
                                        {
                                            active: 1,
                                            nombre: 'Habilitado'
                                        }
                                    ],
                                    valueField: 'active',
                                    queryMode: 'local'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            name: 'ctn_column_rigth_user',
                            width: '45%',
                            docked: 'right',
                            margin: '0 0 0 10',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    validators: function(value) {
                                        if(value.length>100){
                                            return "El apellido supera el tamaño permitido (100)";
                                        }else if(/^([0-9])*$/.test(value)){
                                            return "El apellido tiene caracteres invalidos.(0-9)";
                                        }else{
                                            return true;
                                        }
                                    },
                                    name: 'lastname',
                                    width: '100%',
                                    label: 'Apellido',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Digite un apellido'
                                },
                                {
                                    xtype: 'passwordfield',
                                    id: 'txt_password_usuario',
                                    name: 'password',
                                    width: '100%',
                                    label: 'Contraseña',
                                    labelCls: 'my-text',
                                    placeholder: 'Ingrese o cambie la contraseña'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'cbx_roles_usuario',
                                    name: 'roles',
                                    width: '100%',
                                    label: 'Rol',
                                    labelCls: 'my-text',
                                    required: true,
                                    requiredMessage: 'Seleccione un rol',
                                    displayField: 'role',
                                    store: [
                                        {
                                            id: 1,
                                            role: 'ADMIN'
                                        },
                                        {
                                            id: 2,
                                            role: 'USER'
                                        }
                                    ],
                                    valueField: 'role',
                                    queryMode: 'local'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    name: 'ctn_buttons_frm_user',
                    width: '100%',
                    margin: '10 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'id',
                            label: 'Field'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var form = Ext.getCmp('frmUser');
                                var values = form.getValues();
                                var oldEmail=Ext.getCmp('ctn_user_view').getViewModel().get('oldEmail');
                                var peticion;
                                if (form.validate()){
                                    if(form.getRecord()){
                                        var record = form.getRecord();
                                        record.set(values);
                                        Ext.Ajax.request({
                                            url: 'sesionUsuario/actualizarUsuarios',
                                            method: 'POST',
                                            params: {
                                                active:values.active,
                                                email:values.email,
                                                oldEmail:oldEmail,
                                                firstname:values.firstname,
                                                id:values.id,
                                                lastname:values.lastname,
                                                password:values.password,
                                                roles:values.roles

                                            },
                                            success: function(response, opts) {
                                                Ext.getCmp('ctn_user_view').fn_find_user(null);
                                                Ext.getCmp('data_view_user').setStore('');
                                                Ext.ComponentQuery.query('[itemId=search_field_user]')[0].setValue('');
                                                Ext.getCmp('ctn_user_view').getViewModel().set('filtro',null);
                                                Ext.getCmp('ctn_user_view').getViewModel().set('oldEmail',null);

                                                Ext.toast('Edición Exitosa', 1000);

                                            },
                                            failure: function(response, opts) {
                                                Ext.toast('Error al llevar a cabo el proceso', 1000);
                                            }
                                        });
                                        Ext.getCmp('vtn_generar_usuario').unmask();
                                        Ext.getCmp('vtn_generar_usuario').close();
                                    }else{
                                        form.submit({

                                            url: "sesionUsuario/agregarUsuario",
                                            waitMsg: 'espere',
                                            success: function(response, opts) {

                                                Ext.getCmp('ctn_user_view').fn_find_user(null);
                                                Ext.getCmp('data_view_user').setStore('');
                                                Ext.ComponentQuery.query('[itemId=search_field_user]')[0].setValue('');
                                                Ext.getCmp('ctn_user_view').getViewModel().set('filtro',null);
                                                Ext.getCmp('ctn_user_view').getViewModel().set('oldEmail',null);
                                                var info =Ext.getCmp('ctn_statistics_view').getViewModel().get('filtro');
                                                Ext.getCmp('ctn_statistics_view').fn_find_statistcs(info);
                                                Ext.toast('Creación Exitosa', 1000);

                                            },
                                            failure: function(response, opts) {
                                                Ext.toast('Error al llevar a cabo el proceso', 1000);
                                            }

                                        });
                                        Ext.getCmp('vtn_generar_usuario').unmask();
                                        Ext.getCmp('vtn_generar_usuario').close();

                                    }

                                }else{
                                    Ext.toast('Error al validar el formulario!', 1000);
                                }

                            },
                            cls: 'color-buttons',
                            height: 50,
                            id: 'btn_user',
                            ui: 'round',
                            width: 50,
                            tooltip: 'Continuar proceso',
                            iconCls: 'x-fa fa-check blackIcon'
                        }
                    ]
                }
            ]
        }
    ]

});