/*
 * File: app/model/model_info_count.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('facturaElecWeb.model.model_info_count', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],


    fields: [
        {
            name: 'factura'
        },
        {
            name: 'producto'
        },
        {
            name: 'cliente'
        },
        {
            name: 'empresa'
        },
        {
            name: 'usuario'
        }
    ]

});